### ISSUE TITLE
Paginacion de productos

### ISSUE THREAD

**Issue by CarlosGarcia0006** [software2uis/mfe-catalogo#29]
Como usuario, quiero que los resultados de mi búsqueda se presenten en forma paginada, para poder explorar los productos de manera más ordenada, sencilla y sin sentirme abrumado por una gran cantidad de información en pantalla.

Criterios de aceptacion: 

- Los productos deben dividirse en páginas con un número configurable de productos por página (por ejemplo, 5, 10 o 20).
- El usuario debe poder navegar entre páginas mediante botones o enlaces de "Siguiente", "Anterior", y la selección directa de un número de página.
- La página actual debe estar resaltada de forma visual.

**Comment by guillepinto** [comment]
This issue was closed in #31
