### ISSUE TITLE
Visualización detallada de productos

### ISSUE THREAD

**Issue by CarlosGarcia0006** [software2uis/mfe-catalogo#30]
Como usuario, quiero poder ver los productos con una presentación visual más agradable y detallada, para obtener una mejor experiencia al explorar sus características y decidir mi compra.

Criterios de aceptacion:

- Cada producto debe incluir información clave presentada de manera ordenada y atractiva (nombre, precio, descripción breve, disponibilidad, etc.).
- Las especificaciones y características principales deben estar organizadas en secciones claras, como "Descripción" o "Especificaciones técnicas".
- Las promociones, descuentos o etiquetas referentes deben ser eliminadas de los productos, asi como el campo para las reseñas (Por funcionalidad limitada).
- Debe incluir un botón claro para regresar a la lista de productos o continuar explorando categorías relacionadas.

**Comment by Gabriel2152675** [comment]
Se realiza boton para volver al listado de productos, se arregla estilo para una mejor visualizacion para el usuario, se elimina los datos que no seran necesarios para la descripcion del detalle del producto
